services:
  - type: web
    name: grochain-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: grochain-mongodb
          property: connectionString
      - key: CORS_ORIGIN
        value: https://gro-chain.vercel.app
      - key: FRONTEND_URL
        value: https://gro-chain.vercel.app
      # Email Configuration - Using SMTP for reliability
      - key: EMAIL_PROVIDER
        value: smtp
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_SECURE
        value: "false"
      - key: SMTP_USER
        value: grochain.ng@gmail.com  # Your Gmail address
      - key: SMTP_PASS
        sync: false  # Set your Gmail app password in Render dashboard
      - key: SMTP_FROM
        value: grochain.ng@gmail.com  # Your Gmail address
      # SendGrid Configuration (Backup) - Set these in Render dashboard
      - key: SENDGRID_API_KEY
        sync: false  # Set your SendGrid API key in Render dashboard
      - key: SENDGRID_FROM_EMAIL
        value: grochain.ng@gmail.com
      - key: SENDGRID_FROM_NAME
        value: GroChain
