import { APP_CONFIG } from "@/lib/constants"
import { getTokenFromStorage } from "@/lib/auth-storage"

// Flutterwave payment integration utilities

interface FlutterwaveCheckoutResponse {
  status?: string
  tx_ref?: string
  transaction_id?: string | number
  flw_ref?: string
  amount?: number
  currency?: string
  [key: string]: unknown
}

declare global {
  interface Window {
    FlutterwaveCheckout?: (config: Record<string, unknown>) => void
  }
}

/**
 * Load Flutterwave script dynamically
 */
export const loadFlutterwaveScript = (): Promise<void> => {
  return new Promise((resolve, reject) => {
    if (typeof window !== 'undefined' && window.FlutterwaveCheckout) {
      resolve()
      return
    }

    const existingScript = document.querySelector(
      'script[src="https://checkout.flutterwave.com/v3.js"]'
    )
    if (existingScript) {
      // Script tag exists but FlutterwaveCheckout may already be ready
      if (typeof window !== 'undefined' && window.FlutterwaveCheckout) {
        resolve()
        return
      }
      existingScript.addEventListener('load', () => resolve())
      existingScript.addEventListener('error', () =>
        reject(new Error('Flutterwave script failed to load'))
      )
      return
    }

    const script = document.createElement('script')
    script.src = 'https://checkout.flutterwave.com/v3.js'
    script.async = true
    script.onload = () => resolve()
    script.onerror = () => reject(new Error('Failed to load Flutterwave script'))
    document.head.appendChild(script)
  })
}

export interface FlutterwavePaymentData {
  orderId: string
  amount: number
  email: string
  callbackUrl?: string
  customerName?: string
  phone?: string
  /** Reference generated by the backend during /api/payments/initialize — must be used
   * as-is for the actual charge, since the backend's Transaction record and any webhook
   * reconciliation are keyed on this exact value. */
  reference?: string
}

export interface FlutterwaveResponse {
  status: 'success' | 'failed' | 'cancelled'
  reference?: string
  transaction?: FlutterwaveCheckoutResponse
}

/**
 * Initialize Flutterwave inline checkout
 */
export const initializeFlutterwavePayment = async (
  paymentData: FlutterwavePaymentData,
  onSuccess?: (response: FlutterwaveResponse) => void,
  onClose?: () => void
): Promise<FlutterwaveResponse> => {
  return new Promise(async (resolve, reject) => {
    let settled = false
    const settle = (result: FlutterwaveResponse) => {
      if (settled) return
      settled = true
      if (result.status === 'success') onSuccess?.(result)
      else if (result.status === 'cancelled') onClose?.()
      resolve(result)
    }

    try {
      const configResponse = await fetch(`${APP_CONFIG.api.baseUrl}/api/payments/config`)
      const config = await configResponse.json()

      const publicKey = config.data?.flutterwave?.publicKey

      if (
        !publicKey ||
        publicKey === 'your_flutterwave_public_key' ||
        publicKey === 'FLWPUBK_TEST_your_public_key_here'
      ) {
        throw new Error(
          'Flutterwave is not properly configured. Please contact support or use Paystack instead.'
        )
      }

      if (!paymentData.reference) {
        throw new Error(
          'Missing payment reference — payment was not properly initialized with the server'
        )
      }

      if (!Number.isFinite(paymentData.amount) || paymentData.amount <= 0) {
        throw new Error('Invalid payment amount')
      }

      const flutterwaveConfig = {
        public_key: publicKey,
        tx_ref: paymentData.reference,
        amount: paymentData.amount,
        currency: 'NGN',
        payment_options: 'card,mobilemoney,ussd,banktransfer',
        redirect_url:
          paymentData.callbackUrl || `${window.location.origin}/payment/verify`,
        customer: {
          email: paymentData.email,
          phone_number: paymentData.phone || '',
          name: paymentData.customerName || ''
        },
        customizations: {
          title: 'GroChain Payment',
          description: `Payment for order ${paymentData.orderId}`,
          logo: `${typeof window !== 'undefined' ? window.location.origin : 'http://localhost:3000'}/logo-icon.png`
        },
        meta: {
          order_id: paymentData.orderId,
          customer_name: paymentData.customerName
        },
        callback: (response: FlutterwaveCheckoutResponse) => {
          // Flutterwave can fire callback for non-successful attempts — only treat
          // an explicitly successful charge as paid.
          const ok =
            response?.status === 'successful' || response?.status === 'completed'

          if (!ok) {
            settle({
              status: 'failed',
              reference: response?.tx_ref || paymentData.reference,
              transaction: response
            })
            return
          }

          settle({
            status: 'success',
            reference: response.tx_ref || paymentData.reference,
            transaction: response
          })
        },
        onclose: () => {
          // Flutterwave often fires onclose after a successful callback — ignore if settled.
          settle({ status: 'cancelled' })
        }
      }

      await loadFlutterwaveScript()

      if (typeof window !== 'undefined' && window.FlutterwaveCheckout) {
        window.FlutterwaveCheckout(flutterwaveConfig)
      } else {
        throw new Error('Flutterwave script not available after loading')
      }
    } catch (error) {
      console.error('❌ Flutterwave initialization error:', error)
      reject(
        error instanceof Error
          ? error
          : new Error('Flutterwave payment initialization failed')
      )
    }
  })
}

/**
 * Process payment for an order with Flutterwave
 */
export const processFlutterwaveOrderPayment = async (
  orderId: string,
  amount: number,
  email: string,
  onSuccess?: (response: FlutterwaveResponse) => void,
  onClose?: () => void
): Promise<FlutterwaveResponse> => {
  try {
    const token = getTokenFromStorage()
    const initResponse = await fetch(`${APP_CONFIG.api.baseUrl}/api/payments/initialize`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...(token ? { Authorization: `Bearer ${token}` } : {})
      },
      body: JSON.stringify({
        orderId,
        amount,
        email,
        paymentProvider: 'flutterwave',
        callbackUrl: `${window.location.origin}/payment/verify`
      })
    })

    if (!initResponse.ok) {
      const responseText = await initResponse.text()

      if (responseText.includes('<!DOCTYPE') || responseText.includes('<html>')) {
        throw new Error('Server returned HTML instead of JSON. Check API endpoint.')
      }

      let errorData: { message?: string } | null = null
      try {
        errorData = JSON.parse(responseText)
      } catch {
        // fall through
      }
      if (errorData?.message) {
        throw new Error(errorData.message)
      }
      throw new Error(`Server error: ${initResponse.status} - ${responseText.substring(0, 100)}`)
    }

    const initData = await initResponse.json()

    // Prefer nested/provider reference, then top-level flutterwave.reference, then Transaction.
    const reference: string | undefined =
      initData?.data?.flutterwave?.data?.reference ||
      initData?.data?.flutterwave?.reference ||
      initData?.data?.transaction?.reference

    if (!reference) {
      throw new Error('Server did not return a payment reference')
    }

    // Test mode: skip inline popup and verify directly on the server
    if (initData?.data?.testMode) {
      const verifyRes = await fetch(
        `${APP_CONFIG.api.baseUrl}/api/payments/verify/${encodeURIComponent(reference)}?test_mode=true&paymentProvider=flutterwave`,
        {
          headers: token ? { Authorization: `Bearer ${token}` } : {}
        }
      )
      const verifyData = await verifyRes.json()
      if (verifyData.status === 'success') {
        const result: FlutterwaveResponse = { status: 'success', reference }
        onSuccess?.(result)
        return result
      }
      throw new Error(verifyData.message || 'Test payment verification failed')
    }

    const paymentResult = await initializeFlutterwavePayment(
      {
        orderId,
        amount,
        email,
        callbackUrl: `${window.location.origin}/payment/verify`,
        reference
      },
      undefined,
      onClose
    )

    // Confirm payment with backend so the order is marked paid (inline popup
    // does not always redirect to /payment/verify). Only then notify success.
    if (paymentResult.status === 'success' && paymentResult.reference) {
      const verifyRes = await fetch(
        `${APP_CONFIG.api.baseUrl}/api/payments/verify/${encodeURIComponent(paymentResult.reference)}?paymentProvider=flutterwave`,
        {
          headers: token ? { Authorization: `Bearer ${token}` } : {}
        }
      )
      const verifyData = await verifyRes.json()
      if (verifyData.status !== 'success') {
        throw new Error(verifyData.message || 'Payment verification failed')
      }
      onSuccess?.(paymentResult)
    }

    return paymentResult
  } catch (error: unknown) {
    console.error('❌ Flutterwave payment processing error:', error)
    throw error
  }
}

/**
 * Get payment configuration
 */
export const getFlutterwaveConfig = async () => {
  try {
    const response = await fetch(`${APP_CONFIG.api.baseUrl}/api/payments/config`)
    return await response.json()
  } catch (error) {
    console.error('❌ Failed to get Flutterwave config:', error)
    throw error
  }
}

/**
 * Debug function to check Flutterwave script status
 */
export const checkFlutterwaveStatus = () => {
  if (typeof window === 'undefined') {
    return false
  }

  return typeof window.FlutterwaveCheckout !== 'undefined'
}
