import { APP_CONFIG } from "@/lib/constants"
import { getTokenFromStorage } from "@/lib/auth-storage"

// Paystack payment integration utilities

interface PaystackPop {
  setup: (options: PaystackOptions) => { openIframe: () => void }
}

interface PaystackOptions {
  key: string
  email: string
  amount: number
  currency?: string
  ref?: string
  callback?: (response: PaystackInlineResponse) => void
  onClose?: () => void
}

interface PaystackInlineResponse {
  status: string
  message: string
  reference: string
}

declare global {
  interface Window {
    PaystackPop: PaystackPop
  }
}

/**
 * Load Paystack script dynamically
 */
export const loadPaystackScript = (): Promise<void> => {
  return new Promise((resolve, reject) => {
    // Check if already loaded
    if (typeof window !== 'undefined' && window.PaystackPop) {
      console.log('✅ Paystack script already loaded')
      resolve()
      return
    }

    // Check if script is already in DOM
    const existingScript = document.querySelector('script[src="https://js.paystack.co/v1/inline.js"]')
    if (existingScript) {
      console.log('✅ Paystack script tag exists, waiting for load...')
      existingScript.addEventListener('load', () => {
        console.log('✅ Paystack script loaded via existing tag')
        resolve()
      })
      existingScript.addEventListener('error', () => {
        console.error('❌ Paystack script failed to load via existing tag')
        reject(new Error('Paystack script failed to load'))
      })
      return
    }

    // Create and load script dynamically
    console.log('🔄 Loading Paystack script dynamically...')
    const script = document.createElement('script')
    script.src = 'https://js.paystack.co/v1/inline.js'
    script.async = true

    script.onload = () => {
      console.log('✅ Paystack script loaded dynamically')
      resolve()
    }

    script.onerror = () => {
      console.error('❌ Failed to load Paystack script dynamically')
      reject(new Error('Failed to load Paystack script'))
    }

    document.head.appendChild(script)
  })
}

export interface PaymentData {
  orderId: string
  amount: number
  email: string
  callbackUrl?: string
  /** Reference generated by the backend during /api/payments/initialize — must be used
   * as-is for the actual charge, since the backend's Transaction record and any webhook
   * reconciliation are keyed on this exact value. */
  reference?: string
}

export interface PaystackResponse {
  status: 'success' | 'failed' | 'cancelled'
  reference?: string
  transaction?: Record<string, unknown>
}

/**
 * Initialize Paystack payment
 */
export const initializePaystackPayment = async (
  paymentData: PaymentData,
  onSuccess?: (response: PaystackResponse) => void,
  onClose?: () => void
): Promise<PaystackResponse> => {
  return new Promise(async (resolve, reject) => {
    try {
      // Get Paystack configuration
      const configResponse = await fetch(`${APP_CONFIG.api.baseUrl}/api/payments/config`)
      const config = await configResponse.json()

      // Require backend-provided key; avoid insecure hardcoded fallback
      const publicKey = config.data?.publicKey

      if (!publicKey || publicKey === 'pk_test_your_public_key_here') {
        throw new Error('Paystack public key not configured')
      }

      if (!paymentData.reference) {
        throw new Error('Missing payment reference — payment was not properly initialized with the server')
      }

      const paystackConfig = {
        key: publicKey,
        email: paymentData.email,
        amount: Math.round(paymentData.amount * 100), // Convert to kobo
        currency: 'NGN',
        ref: paymentData.reference,
        callback: (response: PaystackInlineResponse) => {
          console.log('✅ Paystack payment callback:', response)
          const result: PaystackResponse = {
            status: 'success',
            reference: response.reference,
            transaction: { ...response } as Record<string, unknown>
          }
          if (onSuccess) onSuccess(result)
          resolve(result)
        },
        onClose: () => {
          console.log('❌ Paystack payment closed by user')
          const result: PaystackResponse = { status: 'cancelled' }
          if (onClose) onClose()
          resolve(result)
        },
        metadata: {
          order_id: paymentData.orderId,
          custom_fields: [
            {
              display_name: "Order ID",
              variable_name: "order_id",
              value: paymentData.orderId
            }
          ]
        }
      }

      console.log('🔄 Initializing Paystack payment:', paystackConfig)

      // Ensure Paystack script is loaded
      await loadPaystackScript()

      if (typeof window !== 'undefined' && window.PaystackPop) {
        console.log('✅ Initializing Paystack payment modal...')
        const handler = window.PaystackPop.setup(paystackConfig)
        handler.openIframe()
      } else {
        throw new Error('Paystack script not available after loading')
      }

    } catch (error) {
      console.error('❌ Paystack initialization error:', error)
      // Reject with the real error (not a bare {status:'failed'} object) so callers
      // reading error.message get the actual reason instead of a generic fallback.
      reject(error instanceof Error ? error : new Error('Paystack payment initialization failed'))
    }
  })
}

/**
 * Process payment for an order
 */
export const processOrderPayment = async (
  orderId: string,
  amount: number,
  email: string,
  onSuccess?: (response: PaystackResponse) => void,
  onClose?: () => void
): Promise<PaystackResponse> => {
  try {
    console.log('💳 Processing payment for order:', orderId)

    // Initialize payment with backend
    console.log('💳 Initializing payment with backend...')
    console.log('📤 Payment init data:', { orderId, amount, email: email ? '[redacted]' : undefined })

    const token = getTokenFromStorage()
    const initResponse = await fetch(`${APP_CONFIG.api.baseUrl}/api/payments/initialize`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...(token ? { Authorization: `Bearer ${token}` } : {})
      },
      body: JSON.stringify({
        orderId,
        amount,
        email,
        callbackUrl: `${window.location.origin}/payment/verify`
      })
    })

    console.log('📥 Payment init response status:', initResponse.status)
    console.log('📥 Payment init response headers:', Object.fromEntries(initResponse.headers.entries()))

    if (!initResponse.ok) {
      console.log('❌ Payment init failed with status:', initResponse.status)
      const responseText = await initResponse.text()
      console.log('❌ Payment init error response:', responseText)

      // Check if response is HTML
      if (responseText.includes('<!DOCTYPE') || responseText.includes('<html>')) {
        console.log('🚨 CRITICAL: Payment init returned HTML instead of JSON!')
        console.log('🚨 This is causing the "Unexpected token" error')
        throw new Error('Server returned HTML instead of JSON. Check API endpoint.')
      }

      let errorData: { message?: string } | null = null
      try {
        errorData = JSON.parse(responseText)
      } catch {
        // responseText wasn't valid JSON — fall through to the generic message below
      }
      if (errorData?.message) {
        throw new Error(errorData.message)
      }
      throw new Error(`Server error: ${initResponse.status} - ${responseText.substring(0, 100)}`)
    }

    const initData = await initResponse.json()
    console.log('✅ Payment initialized:', initData)

    // The backend generates the authoritative reference and already registered it
    // with Paystack (or a test-mode Transaction) under this exact value — the charge
    // below MUST use it as-is, or server-side verification/webhooks can never match it.
    const reference: string | undefined =
      initData?.data?.paystack?.data?.reference ||
      initData?.data?.paystack?.reference ||
      initData?.data?.transaction?.reference

    if (!reference) {
      throw new Error('Server did not return a payment reference')
    }

    // Test mode: skip inline popup and verify directly on the server
    if (initData?.data?.testMode) {
      const verifyRes = await fetch(
        `${APP_CONFIG.api.baseUrl}/api/payments/verify/${reference}?test_mode=true`,
        {
          headers: token ? { Authorization: `Bearer ${token}` } : {}
        }
      )
      const verifyData = await verifyRes.json()
      if (verifyData.status === 'success') {
        const result: PaystackResponse = { status: 'success', reference }
        onSuccess?.(result)
        return result
      }
      throw new Error(verifyData.message || 'Test payment verification failed')
    }

    // If using Paystack inline (recommended)
    const paymentData: PaymentData = {
      orderId,
      amount,
      email,
      callbackUrl: `${window.location.origin}/payment/verify`,
      reference
    }

    const paymentResult = await initializePaystackPayment(
      paymentData,
      undefined,
      onClose
    )

    // Confirm payment with backend so the order is marked paid (inline popup
    // does not redirect to /payment/verify like the hosted checkout flow).
    // Only notify success after the server confirms — avoids clearing the cart
    // before the order is actually marked paid.
    if (paymentResult.status === 'success' && paymentResult.reference) {
      const verifyRes = await fetch(
        `${APP_CONFIG.api.baseUrl}/api/payments/verify/${encodeURIComponent(paymentResult.reference)}`,
        {
          headers: token ? { Authorization: `Bearer ${token}` } : {}
        }
      )
      const verifyData = await verifyRes.json()
      if (verifyData.status !== 'success') {
        throw new Error(verifyData.message || 'Payment verification failed')
      }
      onSuccess?.(paymentResult)
    }

    return paymentResult

  } catch (error: unknown) {
    console.error('❌ Payment processing error:', error)
    throw error
  }
}

export interface LoanPaymentData {
  loanApplicationId: string
  amount: number
  email: string
  reference?: string
}

/**
 * Process loan repayment via Paystack
 */
export const processLoanPayment = async (
  loanApplicationId: string,
  amount: number,
  email: string,
  onSuccess?: (response: PaystackResponse) => void,
  onClose?: () => void
): Promise<PaystackResponse> => {
  const token = getTokenFromStorage()
  const initResponse = await fetch(`${APP_CONFIG.api.baseUrl}/api/payments/loan/initialize`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...(token ? { Authorization: `Bearer ${token}` } : {})
    },
    body: JSON.stringify({
      loanApplicationId,
      callbackUrl: `${window.location.origin}/payment/verify`
    })
  })

  if (!initResponse.ok) {
    const err = await initResponse.json().catch(() => ({}))
    throw new Error(err.message || 'Failed to initialize loan payment')
  }

  const initData = await initResponse.json()
  const reference =
    initData?.data?.paystack?.data?.reference ||
    initData?.data?.paystack?.reference ||
    initData?.data?.transaction?.reference
  const payAmount = initData?.data?.transaction?.amount || amount

  if (!reference) {
    throw new Error('Server did not return a payment reference')
  }

  if (initData?.data?.testMode) {
    const verifyRes = await fetch(
      `${APP_CONFIG.api.baseUrl}/api/payments/verify/${reference}?test_mode=true`,
      {
        headers: token ? { Authorization: `Bearer ${token}` } : {}
      }
    )
    const verifyData = await verifyRes.json()
    if (verifyData.status === 'success') {
      const result: PaystackResponse = { status: 'success', reference }
      onSuccess?.(result)
      return result
    }
    throw new Error(verifyData.message || 'Test payment verification failed')
  }

  const paymentResult = await initializePaystackPayment(
    { orderId: loanApplicationId, amount: payAmount, email, reference },
    undefined,
    onClose
  )

  if (paymentResult.status === 'success' && paymentResult.reference) {
    const verifyRes = await fetch(
      `${APP_CONFIG.api.baseUrl}/api/payments/verify/${encodeURIComponent(paymentResult.reference)}`,
      {
        headers: token ? { Authorization: `Bearer ${token}` } : {}
      }
    )
    const verifyData = await verifyRes.json()
    if (verifyData.status !== 'success') {
      throw new Error(verifyData.message || 'Payment verification failed')
    }
    onSuccess?.(paymentResult)
  }

  return paymentResult
}

/**
 * Get payment configuration
 */
export const getPaymentConfig = async () => {
  try {
    const response = await fetch(`${APP_CONFIG.api.baseUrl}/api/payments/config`)
    return await response.json()
  } catch (error) {
    console.error('❌ Failed to get payment config:', error)
    throw error
  }
}

/**
 * Debug function to check Paystack script status
 */
export const checkPaystackStatus = () => {
  if (typeof window === 'undefined') {
    console.log('🔍 Running on server-side, window not available')
    return false
  }

  const isLoaded = typeof window.PaystackPop !== 'undefined'
  console.log('🔍 Paystack script status:', {
    loaded: isLoaded,
    scriptTag: !!document.querySelector('script[src="https://js.paystack.co/v1/inline.js"]'),
    paystackPop: isLoaded ? 'Available' : 'Not Available'
  })

  return isLoaded
}
